apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: icdpostgres-app
spec:
  replicas: 3
  template:
    metadata:
      name: icdpostgres-app
      labels:
        run: clouddb-demo
    spec:
      containers:
      - name: cloudpostgres-python-app
        image: "<region>.icr.io/<namespace>/icdpg" # Edit me
        imagePullPolicy: Always
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: binding-icd-postgresql # Edit me
              key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: cloudpostgres-service
  labels:
    run: clouddb-demo
spec:
  type: NodePort
  selector:
    run: clouddb-demo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081